In [1]:
 pip install --upgrade tensorflow-federated

In [2]:
import tensorflow as tf
import tensorflow_federated as tff

In [3]:
import pandas as pd

###Reading the Datasets

In [4]:
#Dataset1
df1 = pd.read_csv('/content/titan.csv')

In [5]:
#Dataset2
df2 = pd.read_csv('/content/dspace.csv')

In [6]:
#Dataset3
df3 = pd.read_csv('/content/dyjns.csv')

In [7]:
#Dataset4
df4 = pd.read_csv('/content/java1.csv')

In [8]:
df5=pd.read_csv("/content/jetty.csv")

In [9]:
print(df2['Failed'].unique())

[False  True]


In [10]:
df6=pd.read_csv("/content/jspirit.csv")

In [11]:
df=[df1,df2,df3,df4,df5,df6]

###Taking Necessary Columns

In [12]:
for i in range(len(df)):
  df[i]=df[i][["Test_Identifier","Failure_Count","Last_Failure_Age","Last_Failure","Failure_Rate","Transition_Count","Last_Transition","#Files_Changed","#Lines_Inserted","#Lines_Deleted","Failed"]]

In [13]:
cols=df[0].columns

In [14]:
cols

Index(['Test_Identifier', 'Failure_Count', 'Last_Failure_Age', 'Last_Failure',
       'Failure_Rate', 'Transition_Count', 'Last_Transition', '#Files_Changed',
       '#Lines_Inserted', '#Lines_Deleted', 'Failed'],
      dtype='object')

###Describing Datasets

In [15]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].info())



for dataset  1 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43257 entries, 0 to 43256
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Test_Identifier   43257 non-null  int64  
 1   Failure_Count     43257 non-null  int64  
 2   Last_Failure_Age  43257 non-null  int64  
 3   Last_Failure      43257 non-null  int64  
 4   Failure_Rate      43028 non-null  float64
 5   Transition_Count  43257 non-null  int64  
 6   Last_Transition   43257 non-null  int64  
 7   #Files_Changed    43257 non-null  int64  
 8   #Lines_Inserted   43257 non-null  int64  
 9   #Lines_Deleted    43257 non-null  int64  
 10  Failed            43257 non-null  bool   
dtypes: bool(1), float64(1), int64(9)
memory usage: 3.3 MB
None


for dataset  2 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122082 entries, 0 to 122081
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------      

###Checking For Null entries

In [16]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].isnull().sum())



for dataset  1 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Failure_Rate        229
Transition_Count      0
Last_Transition       0
#Files_Changed        0
#Lines_Inserted       0
#Lines_Deleted        0
Failed                0
dtype: int64


for dataset  2 


Test_Identifier      0
Failure_Count        0
Last_Failure_Age     0
Last_Failure         0
Failure_Rate        88
Transition_Count     0
Last_Transition      0
#Files_Changed       0
#Lines_Inserted      0
#Lines_Deleted       0
Failed               0
dtype: int64


for dataset  3 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Failure_Rate        169
Transition_Count      0
Last_Transition       0
#Files_Changed        0
#Lines_Inserted       0
#Lines_Deleted        0
Failed                0
dtype: int64


for dataset  4 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Fail

In [17]:
for i in range(len(df)):
  df[i]["Failure_Rate"] = df[i]["Failure_Rate"].fillna(-1)

<ipython-input-17-e0b4f99b3a80>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]["Failure_Rate"] = df[i]["Failure_Rate"].fillna(-1)


In [18]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].isnull().sum())



for dataset  1 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  2 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  3 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  4 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#

###Removing Inf from Failure Rate

In [19]:
for i in range(len(df)):
  print("\n\nDataset ",i+1,"\n\n")
  print(df[i]['Failure_Rate'].unique())



Dataset  1 


[-1.          0.                 inf ...  0.00436205  0.01865672
  0.00435256]


Dataset  2 


[-1.          0.          0.09090909 ...  0.00156576  0.04120879
  0.00338409]


Dataset  3 


[-1.          0.          0.25       ...  0.00966702  0.00429185
  0.0088968 ]


Dataset  4 


[-1.          0.          1.         ...  0.07107232  0.09988109
  0.05162065]


Dataset  5 


[-1.          0.          1.         ...  0.35714286  0.00859599
  0.01432665]


Dataset  6 


[-1.          0.          0.01265823  0.0125             inf  0.01234568
  0.01219512  0.01204819  0.01190476  0.01176471  0.01162791  0.01149425
  0.01136364  0.01123596  0.01111111  0.01098901  0.01086957  0.01075269
  0.0106383   0.01052632  0.01041667  0.01030928  0.01020408  0.01010101
  0.01        0.00990099  0.00980392  0.00970874  1.          0.00961538
  0.83333333  0.00952381  0.71428571  0.00943396  0.625       0.00934579
  0.55555556  0.00925926  0.5         0.00917431  0.45454545  0.0090909

In [20]:
import numpy as np

In [21]:
column_to_fix = 'Failure_Rate'
for i in range(len(df)):
  max_value = df[i][column_to_fix].replace(df[i][column_to_fix].max(), np.nan).max()
  df[i][column_to_fix] = df[i][column_to_fix].replace(df[i][column_to_fix].max(), max_value)

<ipython-input-21-a12aa10b88fd>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][column_to_fix] = df[i][column_to_fix].replace(df[i][column_to_fix].max(), max_value)


In [22]:
for i in range(len(df)):
  print("\n\nDataset ",i+1,"\n\n")
  print(df[i]['Failure_Rate'].unique())



Dataset  1 


[-1.          0.          1.         ...  0.00436205  0.01865672
  0.00435256]


Dataset  2 


[-1.          0.          0.09090909 ...  0.00156576  0.04120879
  0.00338409]


Dataset  3 


[-1.          0.          0.25       ...  0.00966702  0.00429185
  0.0088968 ]


Dataset  4 


[-1.          0.          0.9969697  ...  0.07107232  0.09988109
  0.05162065]


Dataset  5 


[-1.          0.          1.         ...  0.35714286  0.00859599
  0.01432665]


Dataset  6 


[-1.          0.          0.01265823  0.0125      1.          0.01234568
  0.01219512  0.01204819  0.01190476  0.01176471  0.01162791  0.01149425
  0.01136364  0.01123596  0.01111111  0.01098901  0.01086957  0.01075269
  0.0106383   0.01052632  0.01041667  0.01030928  0.01020408  0.01010101
  0.01        0.00990099  0.00980392  0.00970874  0.00961538  0.83333333
  0.00952381  0.71428571  0.00943396  0.625       0.00934579  0.55555556
  0.00925926  0.5         0.00917431  0.45454545  0.00909091  0.4166666

###Encoding Failed Column

In [23]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [24]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i]['Failed'].unique())



for dataset  1 


[False  True]


for dataset  2 


[False  True]


for dataset  3 


[False  True]


for dataset  4 


[False  True]


for dataset  5 


[False  True]


for dataset  6 


[False  True]


In [25]:
for i in range(len(df)):
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])

<ipython-input-25-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])
<ipython-input-25-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])
<ipython-input-25-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: ht

In [26]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i]['Failed'].unique())



for dataset  1 


[0 1]


for dataset  2 


[0 1]


for dataset  3 


[0 1]


for dataset  4 


[0 1]


for dataset  5 


[0 1]


for dataset  6 


[0 1]


###Creating Federated Dataset

In [27]:
from sklearn.utils import resample

In [28]:
pip install imbalanced-learn

In [29]:
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE
import pandas as pd

def upsample_failed(dataset):
    # Impute missing values
    imputer = SimpleImputer()
    dataset_imputed = pd.DataFrame(imputer.fit_transform(dataset), columns=dataset.columns)

    # Split dataset into features and target variable
    X = dataset_imputed.drop('Failed', axis=1)
    y = dataset_imputed['Failed']

    # Apply SMOTE with adjusted parameters
    smote = SMOTE(sampling_strategy='auto', k_neighbors=5, random_state=27)  # Adjust k_neighbors as needed
    X_smote, y_smote = smote.fit_resample(X, y)

    # Concatenate the original dataset with the synthetic samples
    upsampled_dataset = pd.concat([X_smote, y_smote], axis=1)

    # Shuffle the dataset
    upsampled_dataset = upsampled_dataset.sample(frac=1, random_state=42).reset_index(drop=True)

    return upsampled_dataset

In [30]:
d11 = df[0]
d22 = df[1]
d33 = df[2]
d44 = df[3]
d55=df[4]
d66=df[5]

In [31]:
import random

In [32]:
BATCH_SIZE=20

In [33]:
d1=upsample_failed(d11)

In [34]:
features1 = d1.drop(columns=['Failed']).to_numpy(dtype='float32')
labels1 = d1[['Failed']].to_numpy(dtype='float32')

In [35]:
features1[0]

array([ 5.0627407e+01,  7.4849291e+00,  0.0000000e+00,  0.0000000e+00,
        8.5570753e-01,  6.4931613e-01, -5.6712258e-01,  1.5328774e+01,
        9.1821938e+01,  1.0543781e+03], dtype=float32)

In [36]:
labels1[0]

array([1.], dtype=float32)

In [37]:
dataset1 = tf.data.Dataset.from_tensor_slices((features1, labels1))

In [38]:
dataset1=dataset1.batch(BATCH_SIZE)

In [39]:
print(dataset1.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [40]:
d2=upsample_failed(d22)

In [41]:
features2 = d2.drop(columns=['Failed']).to_numpy(dtype='float32')
labels2 = d2[['Failed']].to_numpy(dtype='float32')

In [42]:
dataset2 = tf.data.Dataset.from_tensor_slices((features2, labels2))

In [43]:
dataset2=dataset2.batch(BATCH_SIZE)

In [44]:
print(dataset2.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [45]:
d3=upsample_failed(d33)

In [46]:
features3 = d3.drop(columns=['Failed']).to_numpy(dtype='float32')
labels3 = d3[['Failed']].to_numpy(dtype='float32')

In [47]:
dataset3 = tf.data.Dataset.from_tensor_slices((features3, labels3))

In [48]:
dataset3=dataset3.batch(BATCH_SIZE)

In [49]:
print(dataset3)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [50]:
d4=upsample_failed(d44)

In [51]:
features4 = d4.drop(columns=['Failed']).to_numpy(dtype='float32')
labels4 = d4[['Failed']].to_numpy(dtype='float32')

In [52]:
dataset4 = tf.data.Dataset.from_tensor_slices((features4, labels4))

In [53]:
dataset4=dataset4.batch(BATCH_SIZE)

In [54]:
print(dataset4)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [55]:
d5=upsample_failed(d55)

In [56]:
features5 = d5.drop(columns=['Failed']).to_numpy(dtype='float32')
labels5 = d5[['Failed']].to_numpy(dtype='float32')

In [57]:
features5[0]

array([ 2.810e+02,  0.000e+00, -1.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00, -1.000e+00,  1.540e+02,  3.500e+02,  1.056e+03],
      dtype=float32)

In [58]:
labels5[0]

array([0.], dtype=float32)

In [59]:
dataset5 = tf.data.Dataset.from_tensor_slices((features5, labels5))

In [60]:
dataset5=dataset5.batch(BATCH_SIZE)

In [61]:
print(dataset5.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [62]:
d6=upsample_failed(d66)

In [63]:
features6 = d6.drop(columns=['Failed']).to_numpy(dtype='float32')
labels6 = d6[['Failed']].to_numpy(dtype='float32')

In [64]:
features6[0]

array([ 8.9859024e+01,  1.2259077e-02, -9.6015799e-01,  0.0000000e+00,
       -9.9692273e-01,  2.4518155e-02, -9.7241706e-01,  4.0030646e+00,
        2.6801840e+02,  1.6915403e+03], dtype=float32)

In [65]:
labels6[0]

array([1.], dtype=float32)

In [66]:
dataset6 = tf.data.Dataset.from_tensor_slices((features6, labels6))

In [67]:
dataset6=dataset6.batch(BATCH_SIZE)

In [68]:
print(dataset6.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [69]:
def map_func(feature, label):
    return feature, label

mapped_dataset1 = dataset1.map(map_func)
mapped_dataset2 = dataset2.map(map_func)
mapped_dataset3 = dataset3.map(map_func)
mapped_dataset4 = dataset4.map(map_func)
mapped_dataset5 = dataset5.map(map_func)
mapped_dataset6 = dataset6.map(map_func)

In [70]:
federated_data_tcp=[mapped_dataset1,mapped_dataset2,mapped_dataset3,mapped_dataset5,mapped_dataset6]

In [71]:
federated_data_tcp[0]

<_MapDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [72]:
def create_keras_model():
    return tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(10,)),
        tf.keras.layers.Dense(20),
        tf.keras.layers.Dense(1,activation='sigmoid'),
    ])

In [73]:
def model_fn():
    keras_model = create_keras_model()
    return tff.learning.models.from_keras_model(
        keras_model,
        input_spec=federated_data_tcp[0].element_spec,
        loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[tf.keras.metrics.BinaryAccuracy()]
    )

In [74]:
print(federated_data_tcp[0].element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [75]:
@tff.tf_computation
def server_init():
  model = model_fn()
  print(model.trainable_variables)
  return model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(10, 20) dtype=float32>, <tf.Variable 'dense/bias:0' shape=(20,) dtype=float32>, <tf.Variable 'dense_1/kernel:0' shape=(20, 1) dtype=float32>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32>]


<ipython-input-75-4ad298999871>:2: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  def server_init():


In [76]:
@tf.function
def client_update(model, dataset, server_weights, client_optimizer):

  client_weights = model.trainable_variables

  tf.nest.map_structure(lambda x, y: x.assign(y),
                        client_weights, server_weights)

  for batch in dataset:
    with tf.GradientTape() as tape:

      outputs = model.forward_pass(batch)

    grads = tape.gradient(outputs.loss, client_weights)

    # Apply class weights if provided
#     if class_weights is not None:
#         grads = [grad * weight for grad, weight in zip(grads, class_weights)]
#  #class imbalance problem solved
    grads_and_vars = zip(grads, client_weights)

    client_optimizer.apply_gradients(grads_and_vars)

  return client_weights

In [77]:
@tf.function
def server_update(model, mean_client_weights):
  model_weights = model.trainable_variables
  tf.nest.map_structure(lambda x, y: x.assign(y),
                        model_weights, mean_client_weights)
  return model_weights

In [78]:
@tff.federated_computation
def initialize_fn():
  return tff.federated_value(server_init(), tff.SERVER)

In [79]:
model_weights_type = server_init.type_signature.result

In [80]:
model_weights_type

StructType([TensorType(np.float32, (10, 20)), TensorType(np.float32, (20,)), TensorType(np.float32, (20, 1)), TensorType(np.float32, (1,))]) as list

In [81]:
sample_model = model_fn()

In [82]:
sample_model.input_spec

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))

In [83]:
tf_dataset_type = tff.SequenceType(tff.types.tensorflow_to_type(sample_model.input_spec))

In [84]:
tf_dataset_type

SequenceType(StructType([TensorType(np.float32, (None, 10)), TensorType(np.float32, (None, 1))]) as tuple)

In [85]:
@tff.tf_computation(tf_dataset_type, model_weights_type)
def client_update_fn(tf_dataset, server_weights):
  model = model_fn()
  client_optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
  return client_update(model, tf_dataset, server_weights, client_optimizer)

<ipython-input-85-8de644794af4>:1: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  @tff.tf_computation(tf_dataset_type, model_weights_type)


In [86]:
@tff.tf_computation(model_weights_type)
def server_update_fn(mean_client_weights):
  model = model_fn()
  return server_update(model, mean_client_weights)

<ipython-input-86-56510bdb54ec>:1: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  @tff.tf_computation(model_weights_type)


In [87]:
str(model_weights_type)

'<float32[10,20],float32[20],float32[20,1],float32[1]>'

In [88]:
federated_server_type = tff.FederatedType(model_weights_type, tff.SERVER)
federated_dataset_type = tff.FederatedType(tf_dataset_type, tff.CLIENTS)

In [89]:
@tff.federated_computation(federated_server_type, federated_dataset_type)
def next_fn(server_weights, federated_dataset):

  server_weights_at_client = tff.federated_broadcast(server_weights)

  client_weights = tff.federated_map(
      client_update_fn, (federated_dataset, server_weights_at_client))

  mean_client_weights = tff.federated_mean(client_weights)

  server_weights = tff.federated_map(server_update_fn, mean_client_weights)

  return server_weights

In [90]:
federated_algorithm = tff.templates.IterativeProcess(
    initialize_fn=initialize_fn,
    next_fn=next_fn
)

In [91]:
def evaluate(server_state):
  keras_model = create_keras_model()
  keras_model.compile(
      loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[tf.keras.metrics.BinaryAccuracy()]
  )
  keras_model.set_weights(server_state)
  keras_model.evaluate(mapped_dataset4)
  return keras_model

In [92]:
# class_weights={0:0.2,1:0.8}

In [93]:
server_state = federated_algorithm.initialize()

In [94]:
evaluate(server_state)

16418/16418 [==============================] - 57s 3ms/step - loss: 234.3942 - binary_accuracy: 0.5014


In [95]:
for round in range(20):
  server_state = federated_algorithm.next(server_state, federated_data_tcp)

In [96]:
model=evaluate(server_state)

16418/16418 [==============================] - 27s 2ms/step - loss: 10.9438 - binary_accuracy: 0.5684


In [97]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [98]:
def predict(server_state,input):
  keras_model=create_keras_model()
  keras_model.set_weights(server_state)
  predicted=keras_model.predict(input)
  return predicted

In [99]:
inp=features1

In [100]:
label=labels1

In [101]:
predicted=predict(server_state,inp)

2670/2670 [==============================] - 4s 1ms/step


In [102]:
binary_crossentropy = tf.keras.losses.BinaryCrossentropy()(label, predicted)

In [103]:
binary_crossentropy

<tf.Tensor: shape=(), dtype=float32, numpy=0.8720555>

In [104]:
binary_predictions = (predicted >= 0.5).astype(int)

In [105]:
true_values = np.array(label, dtype=int)
binary_predictions = np.array(binary_predictions, dtype=int)

In [106]:
accuracy_score(binary_predictions,true_values)

0.8269563995691472

In [107]:
report = classification_report(y_pred=binary_predictions,y_true=true_values)

In [108]:
print(report)

              precision    recall  f1-score   support

           0       0.80      0.87      0.83     42706
           1       0.86      0.78      0.82     42706

    accuracy                           0.83     85412
   macro avg       0.83      0.83      0.83     85412
weighted avg       0.83      0.83      0.83     85412



In [109]:
cnf_mat = confusion_matrix(y_true=true_values,y_pred=binary_predictions)

In [110]:
print(cnf_mat)

[[37338  5368]
 [ 9412 33294]]


In [111]:
print(binary_predictions)

[[1]
 [0]
 [1]
 ...
 [0]
 [0]
 [0]]


In [112]:
resampled_df1 = d4.sample(n=10)
print(resampled_df1)

        Test_Identifier  Failure_Count  Last_Failure_Age  Last_Failure  \
93197        267.000000      59.000000          5.000000      0.000000   
61153        162.078014      13.893174          0.000000      0.000000   
14999        271.645589      57.296730          0.000000      0.000000   
132891       271.949143      55.016952          0.998305      0.998305   
190786        72.901875      39.327084          0.000000      0.000000   
107802         7.000000      47.000000         25.000000      0.000000   
104754       269.774145      28.936118          5.419014      0.000000   
245551        20.376661      21.196759         71.639222      0.000000   
57823        268.000000     168.000000          7.000000      0.000000   
307237        61.000000      26.000000          2.000000      0.000000   

        Failure_Rate  Transition_Count  Last_Transition  #Files_Changed  \
93197       0.353293         15.000000         4.000000        2.000000   
61153       0.086266          6.144

In [113]:
features_rs = resampled_df1.drop(columns=['Failed']).to_numpy(dtype='float32')
labelsrs = resampled_df1[['Failed']].to_numpy(dtype='float32')

In [114]:
features_rs

array([[2.6700000e+02, 5.9000000e+01, 5.0000000e+00, 0.0000000e+00,
        3.5329342e-01, 1.5000000e+01, 4.0000000e+00, 2.0000000e+00,
        1.9900000e+02, 1.0620000e+03],
       [1.6207802e+02, 1.3893174e+01, 0.0000000e+00, 0.0000000e+00,
        8.6266272e-02, 6.1440601e+00, 9.4609928e+00, 6.1498226e+01,
        1.7494813e+03, 1.5724897e+03],
       [2.7164560e+02, 5.7296730e+01, 0.0000000e+00, 0.0000000e+00,
        3.3632225e-01, 1.7466997e+01, 0.0000000e+00, 1.2587909e+01,
        2.2106323e+02, 1.7079479e+03],
       [2.7194916e+02, 5.5016953e+01, 9.9830478e-01, 9.9830478e-01,
        1.4240092e-01, 2.8064419e+01, 0.0000000e+00, 1.0050857e+00,
        1.8190068e+03, 1.2360000e+03],
       [7.2901878e+01, 3.9327084e+01, 0.0000000e+00, 0.0000000e+00,
        7.5595134e-01, 6.2269645e+00, 1.4259673e+01, 6.0654168e+00,
        9.5616351e+02, 7.7715955e+02],
       [7.0000000e+00, 4.7000000e+01, 2.5000000e+01, 0.0000000e+00,
        6.5459609e-02, 3.1000000e+01, 2.4000000e+01, 1.00

In [115]:
predict_rs=predict(server_state,features_rs)

1/1 [==============================] - 0s 68ms/step


In [116]:
predict_rs

array([[1.        ],
       [0.99999404],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.9997104 ],
       [1.        ],
       [1.        ]], dtype=float32)

In [117]:
labelsrs

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [118]:
merged_rs = np.concatenate((features_rs, predict_rs), axis=1)
print(merged_rs)

[[2.6700000e+02 5.9000000e+01 5.0000000e+00 0.0000000e+00 3.5329342e-01
  1.5000000e+01 4.0000000e+00 2.0000000e+00 1.9900000e+02 1.0620000e+03
  1.0000000e+00]
 [1.6207802e+02 1.3893174e+01 0.0000000e+00 0.0000000e+00 8.6266272e-02
  6.1440601e+00 9.4609928e+00 6.1498226e+01 1.7494813e+03 1.5724897e+03
  9.9999404e-01]
 [2.7164560e+02 5.7296730e+01 0.0000000e+00 0.0000000e+00 3.3632225e-01
  1.7466997e+01 0.0000000e+00 1.2587909e+01 2.2106323e+02 1.7079479e+03
  1.0000000e+00]
 [2.7194916e+02 5.5016953e+01 9.9830478e-01 9.9830478e-01 1.4240092e-01
  2.8064419e+01 0.0000000e+00 1.0050857e+00 1.8190068e+03 1.2360000e+03
  1.0000000e+00]
 [7.2901878e+01 3.9327084e+01 0.0000000e+00 0.0000000e+00 7.5595134e-01
  6.2269645e+00 1.4259673e+01 6.0654168e+00 9.5616351e+02 7.7715955e+02
  1.0000000e+00]
 [7.0000000e+00 4.7000000e+01 2.5000000e+01 0.0000000e+00 6.5459609e-02
  3.1000000e+01 2.4000000e+01 1.0000000e+00 4.2500000e+02 1.6240000e+03
  1.0000000e+00]
 [2.6977414e+02 2.8936117e+01 5.41

In [119]:
mindex = np.concatenate((np.arange(len(merged_rs)).reshape(-1, 1), merged_rs), axis=1)

In [120]:
mindex

array([[0.00000000e+00, 2.67000000e+02, 5.90000000e+01, 5.00000000e+00,
        0.00000000e+00, 3.53293419e-01, 1.50000000e+01, 4.00000000e+00,
        2.00000000e+00, 1.99000000e+02, 1.06200000e+03, 1.00000000e+00],
       [1.00000000e+00, 1.62078018e+02, 1.38931742e+01, 0.00000000e+00,
        0.00000000e+00, 8.62662718e-02, 6.14406013e+00, 9.46099281e+00,
        6.14982262e+01, 1.74948132e+03, 1.57248975e+03, 9.99994040e-01],
       [2.00000000e+00, 2.71645599e+02, 5.72967300e+01, 0.00000000e+00,
        0.00000000e+00, 3.36322248e-01, 1.74669971e+01, 0.00000000e+00,
        1.25879087e+01, 2.21063232e+02, 1.70794788e+03, 1.00000000e+00],
       [3.00000000e+00, 2.71949158e+02, 5.50169525e+01, 9.98304784e-01,
        9.98304784e-01, 1.42400920e-01, 2.80644188e+01, 0.00000000e+00,
        1.00508571e+00, 1.81900684e+03, 1.23600000e+03, 1.00000000e+00],
       [4.00000000e+00, 7.29018784e+01, 3.93270836e+01, 0.00000000e+00,
        0.00000000e+00, 7.55951345e-01, 6.22696447e+00, 1.42

In [121]:
sindex = mindex[mindex[:, -1].argsort()[::-1]]
sindex

array([[9.00000000e+00, 6.10000000e+01, 2.60000000e+01, 2.00000000e+00,
        0.00000000e+00, 6.26506060e-02, 1.80000000e+01, 1.00000000e+00,
        1.00000000e+00, 8.15000000e+02, 2.30000000e+02, 1.00000000e+00],
       [8.00000000e+00, 2.68000000e+02, 1.68000000e+02, 7.00000000e+00,
        0.00000000e+00, 2.28260875e-01, 6.00000000e+01, 6.00000000e+00,
        1.18400000e+03, 1.93000000e+03, 1.25100000e+03, 1.00000000e+00],
       [6.00000000e+00, 2.69774139e+02, 2.89361172e+01, 5.41901350e+00,
        0.00000000e+00, 2.40537345e-01, 7.83878279e+00, 1.48387833e+01,
        6.80311890e+01, 9.15000732e+02, 1.15987219e+03, 1.00000000e+00],
       [5.00000000e+00, 7.00000000e+00, 4.70000000e+01, 2.50000000e+01,
        0.00000000e+00, 6.54596090e-02, 3.10000000e+01, 2.40000000e+01,
        1.00000000e+00, 4.25000000e+02, 1.62400000e+03, 1.00000000e+00],
       [4.00000000e+00, 7.29018784e+01, 3.93270836e+01, 0.00000000e+00,
        0.00000000e+00, 7.55951345e-01, 6.22696447e+00, 1.42

In [122]:
print(sindex[:,0])
print(sindex[:,-1])

[9. 8. 6. 5. 4. 3. 2. 0. 1. 7.]
[1.         1.         1.         1.         1.         1.
 1.         1.         0.99999404 0.99971038]


In [123]:
labelsrs

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.]], dtype=float32)