In [1]:
 pip install --upgrade tensorflow-federated

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 MB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 10.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.6/721.6 kB 28.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.7/73.7 MB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.7/33.7 MB 30.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 262.5/262.5 kB 26.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 27.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.2/323.2 kB 33.2 MB/s eta 0:00:00
     ━━━━

In [1]:
import tensorflow as tf
import tensorflow_federated as tff

In [2]:
import pandas as pd

###Reading the Datasets

In [3]:
#Dataset1
df1 = pd.read_csv('/content/titan.csv')

In [4]:
#Dataset2
df2 = pd.read_csv('/content/dspace.csv')

In [5]:
#Dataset3
df3 = pd.read_csv('/content/dyjns.csv')

In [6]:
#Dataset4
df4 = pd.read_csv('/content/java1.csv')

In [7]:
df5=pd.read_csv("/content/jetty.csv")

In [8]:
df6=pd.read_csv("/content/jspirit.csv")

In [9]:
df=[df1,df2,df3,df4,df5,df6]

###Taking Necessary Columns

In [10]:
for i in range(len(df)):
  df[i]=df[i][["Test_Identifier","Failure_Count","Last_Failure_Age","Last_Failure","Failure_Rate","Transition_Count","Last_Transition","#Files_Changed","#Lines_Inserted","#Lines_Deleted","Failed"]]

In [11]:
cols=df[0].columns

In [12]:
cols

Index(['Test_Identifier', 'Failure_Count', 'Last_Failure_Age', 'Last_Failure',
       'Failure_Rate', 'Transition_Count', 'Last_Transition', '#Files_Changed',
       '#Lines_Inserted', '#Lines_Deleted', 'Failed'],
      dtype='object')

###Describing Datasets

In [13]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].info())



for dataset  1 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43257 entries, 0 to 43256
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Test_Identifier   43257 non-null  int64  
 1   Failure_Count     43257 non-null  int64  
 2   Last_Failure_Age  43257 non-null  int64  
 3   Last_Failure      43257 non-null  int64  
 4   Failure_Rate      43028 non-null  float64
 5   Transition_Count  43257 non-null  int64  
 6   Last_Transition   43257 non-null  int64  
 7   #Files_Changed    43257 non-null  int64  
 8   #Lines_Inserted   43257 non-null  int64  
 9   #Lines_Deleted    43257 non-null  int64  
 10  Failed            43257 non-null  bool   
dtypes: bool(1), float64(1), int64(9)
memory usage: 3.3 MB
None


for dataset  2 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122082 entries, 0 to 122081
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------      

###Checking For NUll entries

In [14]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].isnull().sum())



for dataset  1 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Failure_Rate        229
Transition_Count      0
Last_Transition       0
#Files_Changed        0
#Lines_Inserted       0
#Lines_Deleted        0
Failed                0
dtype: int64


for dataset  2 


Test_Identifier      0
Failure_Count        0
Last_Failure_Age     0
Last_Failure         0
Failure_Rate        88
Transition_Count     0
Last_Transition      0
#Files_Changed       0
#Lines_Inserted      0
#Lines_Deleted       0
Failed               0
dtype: int64


for dataset  3 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Failure_Rate        169
Transition_Count      0
Last_Transition       0
#Files_Changed        0
#Lines_Inserted       0
#Lines_Deleted        0
Failed                0
dtype: int64


for dataset  4 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Fail

In [15]:
for i in range(len(df)):
  df[i]["Failure_Rate"] = df[i]["Failure_Rate"].fillna(-1)

<ipython-input-15-e0b4f99b3a80>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]["Failure_Rate"] = df[i]["Failure_Rate"].fillna(-1)


In [16]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].isnull().sum())



for dataset  1 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  2 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  3 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  4 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#

###Removing Inf from Failure Rate

In [17]:
for i in range(len(df)):
  print("\n\nDataset ",i+1,"\n\n")
  print(df[i]['Failure_Rate'].unique())



Dataset  1 


[-1.          0.                 inf ...  0.00436205  0.01865672
  0.00435256]


Dataset  2 


[-1.          0.          0.09090909 ...  0.00156576  0.04120879
  0.00338409]


Dataset  3 


[-1.          0.          0.25       ...  0.00966702  0.00429185
  0.0088968 ]


Dataset  4 


[-1.          0.          1.         ...  0.07107232  0.09988109
  0.05162065]


Dataset  5 


[-1.          0.          1.         ...  0.35714286  0.00859599
  0.01432665]


Dataset  6 


[-1.          0.          0.01265823  0.0125             inf  0.01234568
  0.01219512  0.01204819  0.01190476  0.01176471  0.01162791  0.01149425
  0.01136364  0.01123596  0.01111111  0.01098901  0.01086957  0.01075269
  0.0106383   0.01052632  0.01041667  0.01030928  0.01020408  0.01010101
  0.01        0.00990099  0.00980392  0.00970874  1.          0.00961538
  0.83333333  0.00952381  0.71428571  0.00943396  0.625       0.00934579
  0.55555556  0.00925926  0.5         0.00917431  0.45454545  0.0090909

In [18]:
import numpy as np

In [19]:
column_to_fix = 'Failure_Rate'
for i in range(len(df)):
  max_value = df[i][column_to_fix].replace(df[i][column_to_fix].max(), np.nan).max()
  df[i][column_to_fix] = df[i][column_to_fix].replace(df[i][column_to_fix].max(), max_value)

<ipython-input-19-a12aa10b88fd>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][column_to_fix] = df[i][column_to_fix].replace(df[i][column_to_fix].max(), max_value)


In [20]:
for i in range(len(df)):
  print("\n\nDataset ",i+1,"\n\n")
  print(df[i]['Failure_Rate'].unique())



Dataset  1 


[-1.          0.          1.         ...  0.00436205  0.01865672
  0.00435256]


Dataset  2 


[-1.          0.          0.09090909 ...  0.00156576  0.04120879
  0.00338409]


Dataset  3 


[-1.          0.          0.25       ...  0.00966702  0.00429185
  0.0088968 ]


Dataset  4 


[-1.          0.          0.9969697  ...  0.07107232  0.09988109
  0.05162065]


Dataset  5 


[-1.          0.          1.         ...  0.35714286  0.00859599
  0.01432665]


Dataset  6 


[-1.          0.          0.01265823  0.0125      1.          0.01234568
  0.01219512  0.01204819  0.01190476  0.01176471  0.01162791  0.01149425
  0.01136364  0.01123596  0.01111111  0.01098901  0.01086957  0.01075269
  0.0106383   0.01052632  0.01041667  0.01030928  0.01020408  0.01010101
  0.01        0.00990099  0.00980392  0.00970874  0.00961538  0.83333333
  0.00952381  0.71428571  0.00943396  0.625       0.00934579  0.55555556
  0.00925926  0.5         0.00917431  0.45454545  0.00909091  0.4166666

###Encoding Failed Column

In [21]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [22]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i]['Failed'].unique())



for dataset  1 


[False  True]


for dataset  2 


[False  True]


for dataset  3 


[False  True]


for dataset  4 


[False  True]


for dataset  5 


[False  True]


for dataset  6 


[False  True]


In [23]:
for i in range(len(df)):
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])

<ipython-input-23-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])
<ipython-input-23-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])
<ipython-input-23-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: ht

In [24]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i]['Failed'].unique())



for dataset  1 


[0 1]


for dataset  2 


[0 1]


for dataset  3 


[0 1]


for dataset  4 


[0 1]


for dataset  5 


[0 1]


for dataset  6 


[0 1]


###Creating Federated Dataset

In [25]:
from sklearn.utils import resample

In [26]:
def upsample_failed(dataset):
  failed_rows = dataset[dataset['Failed'] == 1]


  upsampled_failed_rows = resample(failed_rows,
                                  replace=True,
                                  n_samples=len(dataset) - len(failed_rows),
                                  random_state=27)

  upsampled_dataset = pd.concat([dataset, upsampled_failed_rows])
  upsampled_dataset = upsampled_dataset.sample(frac=1, random_state=42).reset_index(drop=True)
  return upsampled_dataset

In [27]:
d11 = df[0]
d22 = df[1]
d33 = df[2]
d44 = df[3]
d55=df[4]
d66=df[5]

In [28]:
import random

In [29]:
BATCH_SIZE=20

In [30]:
d1=upsample_failed(d11)

In [31]:
features1 = d1.drop(columns=['Failed']).to_numpy(dtype='float32')
labels1 = d1[['Failed']].to_numpy(dtype='float32')

In [32]:
features1[0]

array([4.1000000e+01, 6.1000000e+01, 1.0200000e+02, 0.0000000e+00,
       3.2446808e-01, 5.0000000e+00, 8.7000000e+01, 4.0000000e+00,
       1.9280000e+03, 1.0440000e+03], dtype=float32)

In [33]:
labels1[0]

array([0.], dtype=float32)

In [34]:
dataset1 = tf.data.Dataset.from_tensor_slices((features1, labels1))

In [35]:
dataset1=dataset1.batch(BATCH_SIZE)

In [36]:
print(dataset1.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [37]:
d2=upsample_failed(d22)

In [38]:
features2 = d2.drop(columns=['Failed']).to_numpy(dtype='float32')
labels2 = d2[['Failed']].to_numpy(dtype='float32')

In [39]:
dataset2 = tf.data.Dataset.from_tensor_slices((features2, labels2))

In [40]:
dataset2=dataset2.batch(BATCH_SIZE)

In [41]:
print(dataset2.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [42]:
d3=upsample_failed(d33)

In [43]:
features3 = d3.drop(columns=['Failed']).to_numpy(dtype='float32')
labels3 = d3[['Failed']].to_numpy(dtype='float32')

In [44]:
dataset3 = tf.data.Dataset.from_tensor_slices((features3, labels3))

In [45]:
dataset3=dataset3.batch(BATCH_SIZE)

In [46]:
print(dataset3)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [47]:
d4=upsample_failed(d44)

In [48]:
features4 = d4.drop(columns=['Failed']).to_numpy(dtype='float32')
labels4 = d4[['Failed']].to_numpy(dtype='float32')

In [49]:
dataset4 = tf.data.Dataset.from_tensor_slices((features4, labels4))

In [50]:
dataset4=dataset4.batch(BATCH_SIZE)

In [51]:
print(dataset4)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [52]:
d5=upsample_failed(d55)

In [53]:
features5 = d5.drop(columns=['Failed']).to_numpy(dtype='float32')
labels5 = d5[['Failed']].to_numpy(dtype='float32')

In [54]:
features5[0]

array([ 3.000e+00,  0.000e+00, -1.000e+00,  0.000e+00,  0.000e+00,
        1.000e+01,  0.000e+00,  1.000e+00,  9.780e+02,  1.502e+03],
      dtype=float32)

In [55]:
labels5[0]

array([0.], dtype=float32)

In [56]:
dataset5 = tf.data.Dataset.from_tensor_slices((features5, labels5))

In [57]:
dataset5=dataset5.batch(BATCH_SIZE)

In [58]:
print(dataset5.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [59]:
d6=upsample_failed(d66)

In [60]:
features6 = d6.drop(columns=['Failed']).to_numpy(dtype='float32')
labels6 = d6[['Failed']].to_numpy(dtype='float32')

In [61]:
features6[0]

array([ 1.020e+02,  3.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,
        0.000e+00, -1.000e+00,  1.040e+02,  1.703e+03,  8.080e+02],
      dtype=float32)

In [62]:
labels6[0]

array([1.], dtype=float32)

In [63]:
dataset6 = tf.data.Dataset.from_tensor_slices((features6, labels6))

In [64]:
dataset6=dataset6.batch(BATCH_SIZE)

In [65]:
print(dataset6.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [66]:
def map_func(feature, label):
    return feature, label

mapped_dataset1 = dataset1.map(map_func)
mapped_dataset2 = dataset2.map(map_func)
mapped_dataset3 = dataset3.map(map_func)
mapped_dataset4 = dataset4.map(map_func)
mapped_dataset5 = dataset5.map(map_func)
mapped_dataset6 = dataset6.map(map_func)

In [67]:
federated_data_tcp=[mapped_dataset1,mapped_dataset2,mapped_dataset3,mapped_dataset5,mapped_dataset6]

In [68]:
federated_data_tcp[0]

<_MapDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [69]:
def create_keras_model():
    return tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(10,)),
        tf.keras.layers.Dense(20),
        tf.keras.layers.Dense(1,activation='sigmoid'),
    ])

In [70]:
def model_fn():
    keras_model = create_keras_model()
    return tff.learning.models.from_keras_model(
        keras_model,
        input_spec=federated_data_tcp[0].element_spec,
        loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[tf.keras.metrics.BinaryAccuracy()]
    )

In [71]:
print(federated_data_tcp[0].element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [72]:
@tff.tf_computation
def server_init():
  model = model_fn()
  print(model.trainable_variables)
  return model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(10, 20) dtype=float32>, <tf.Variable 'dense/bias:0' shape=(20,) dtype=float32>, <tf.Variable 'dense_1/kernel:0' shape=(20, 1) dtype=float32>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32>]


<ipython-input-72-4ad298999871>:2: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  def server_init():


In [73]:
@tf.function
def client_update(model, dataset, server_weights, client_optimizer):
    client_weights = model.trainable_variables

    tf.nest.map_structure(lambda x, y: x.assign(y),
                          client_weights, server_weights)

    for batch in dataset:
        with tf.GradientTape() as tape:
            outputs = model.forward_pass(batch)

        grads = tape.gradient(outputs.loss, client_weights)

        # Apply class weights if provided
        if class_weights is not None:
            grads = [grad * weight for grad, weight in zip(grads, class_weights)]

        grads_and_vars = zip(grads, client_weights)

        client_optimizer.apply_gradients(grads_and_vars)

    return client_weights


In [74]:
@tf.function
def server_update(model, mean_client_weights):
  model_weights = model.trainable_variables
  tf.nest.map_structure(lambda x, y: x.assign(y),
                        model_weights, mean_client_weights)
  return model_weights

In [75]:
@tff.federated_computation
def initialize_fn():
  return tff.federated_value(server_init(), tff.SERVER)

In [76]:
model_weights_type = server_init.type_signature.result

In [77]:
model_weights_type

StructType([TensorType(np.float32, (10, 20)), TensorType(np.float32, (20,)), TensorType(np.float32, (20, 1)), TensorType(np.float32, (1,))]) as list

In [78]:
sample_model = model_fn()

In [79]:
sample_model.input_spec

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))

In [80]:
tf_dataset_type = tff.SequenceType(tff.types.tensorflow_to_type(sample_model.input_spec))

In [81]:
tf_dataset_type

SequenceType(StructType([TensorType(np.float32, (None, 10)), TensorType(np.float32, (None, 1))]) as tuple)

In [83]:
class_weights={0:0.2,1:0.8}

In [84]:
@tff.tf_computation(tf_dataset_type, model_weights_type)
def client_update_fn(tf_dataset, server_weights):
  model = model_fn()
  client_optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
  return client_update(model, tf_dataset, server_weights, client_optimizer)

<ipython-input-84-8de644794af4>:1: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  @tff.tf_computation(tf_dataset_type, model_weights_type)


In [85]:
@tff.tf_computation(model_weights_type)
def server_update_fn(mean_client_weights):
  model = model_fn()
  return server_update(model, mean_client_weights)

<ipython-input-85-56510bdb54ec>:1: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  @tff.tf_computation(model_weights_type)


In [86]:
str(model_weights_type)

'<float32[10,20],float32[20],float32[20,1],float32[1]>'

In [87]:
federated_server_type = tff.FederatedType(model_weights_type, tff.SERVER)
federated_dataset_type = tff.FederatedType(tf_dataset_type, tff.CLIENTS)

In [88]:
@tff.federated_computation(federated_server_type, federated_dataset_type)
def next_fn(server_weights, federated_dataset):

  server_weights_at_client = tff.federated_broadcast(server_weights)

  client_weights = tff.federated_map(
      client_update_fn, (federated_dataset, server_weights_at_client))

  mean_client_weights = tff.federated_mean(client_weights)

  server_weights = tff.federated_map(server_update_fn, mean_client_weights)

  return server_weights

In [89]:
federated_algorithm = tff.templates.IterativeProcess(
    initialize_fn=initialize_fn,
    next_fn=next_fn
)

In [90]:
def evaluate(server_state):
  keras_model = create_keras_model()
  keras_model.compile(
      loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[tf.keras.metrics.BinaryAccuracy()]
  )
  keras_model.set_weights(server_state)
  keras_model.evaluate(mapped_dataset4)
  return keras_model

SMOTE

In [91]:
server_state = federated_algorithm.initialize()

In [92]:
evaluate(server_state)

17147/17147 [==============================] - 45s 3ms/step - loss: 276.7881 - binary_accuracy: 0.4861


In [93]:
for round in range(30):
  server_state = federated_algorithm.next(server_state, federated_data_tcp)

In [94]:
model=evaluate(server_state)

17147/17147 [==============================] - 30s 2ms/step - loss: 283.5819 - binary_accuracy: 0.4850


In [95]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [96]:
def predict(server_state,input):
  keras_model=create_keras_model()
  keras_model.set_weights(server_state)
  predicted=keras_model.predict(input)
  return predicted

In [97]:
inp=features1

In [98]:
label=labels1

In [99]:
predicted=predict(server_state,inp)

2687/2687 [==============================] - 4s 1ms/step


In [100]:
binary_crossentropy = tf.keras.losses.BinaryCrossentropy()(label, predicted)

In [101]:
binary_crossentropy

<tf.Tensor: shape=(), dtype=float32, numpy=7.8956804>

In [102]:
binary_predictions = (predicted >= 0.5).astype(int)

In [103]:
true_values = np.array(label, dtype=int)
binary_predictions = np.array(binary_predictions, dtype=int)

In [104]:
accuracy_score(binary_predictions,true_values)

0.48327768923839326

In [105]:
report = classification_report(y_pred=binary_predictions,y_true=true_values)

In [106]:
print(report)

              precision    recall  f1-score   support

           0       0.49      0.78      0.60     42706
           1       0.47      0.19      0.27     43257

    accuracy                           0.48     85963
   macro avg       0.48      0.49      0.44     85963
weighted avg       0.48      0.48      0.44     85963



In [107]:
cnf_mat = confusion_matrix(y_true=true_values,y_pred=binary_predictions)

In [108]:
print(cnf_mat)

[[33172  9534]
 [34885  8372]]


In [109]:
print(binary_predictions)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [110]:
resampled_df1 = d4.sample(n=10)
print(resampled_df1)


        Test_Identifier  Failure_Count  Last_Failure_Age  Last_Failure  \
270980              278             60                23             0   
252570              266             22                 0             0   
202376              214            104                 2             0   
141103              235             52                 2             0   
266045              234             41                 0             0   
63413               112              4                29             0   
68985               237             28                12             0   
44216               195             17                 0             0   
205469               93             19                47             0   
225860               87              0                -1             0   

        Failure_Rate  Transition_Count  Last_Transition  #Files_Changed  \
270980      0.079681                37               22               3   
252570      0.112245               

In [111]:
features_rs = resampled_df1.drop(columns=['Failed']).to_numpy(dtype='float32')
labelsrs = resampled_df1[['Failed']].to_numpy(dtype='float32')

In [112]:
features_rs

array([[ 2.7800000e+02,  6.0000000e+01,  2.3000000e+01,  0.0000000e+00,
         7.9681277e-02,  3.7000000e+01,  2.2000000e+01,  3.0000000e+00,
         7.9200000e+02,  7.0000000e+02],
       [ 2.6600000e+02,  2.2000000e+01,  0.0000000e+00,  0.0000000e+00,
         1.1224490e-01,  1.1000000e+01,  6.0000000e+00,  2.0000000e+01,
         9.6400000e+02,  4.7100000e+02],
       [ 2.1400000e+02,  1.0400000e+02,  2.0000000e+00,  0.0000000e+00,
         2.2127660e-01,  3.1000000e+01,  1.0000000e+00,  1.0200000e+02,
         2.1600000e+02,  1.1970000e+03],
       [ 2.3500000e+02,  5.2000000e+01,  2.0000000e+00,  0.0000000e+00,
         6.6411242e-02,  5.1000000e+01,  1.0000000e+00,  1.5000000e+01,
         4.2400000e+02,  1.8880000e+03],
       [ 2.3400000e+02,  4.1000000e+01,  0.0000000e+00,  0.0000000e+00,
         8.5774057e-02,  2.7000000e+01,  3.0000000e+00,  2.4000000e+01,
         1.1000000e+01,  8.7000000e+01],
       [ 1.1200000e+02,  4.0000000e+00,  2.9000000e+01,  0.0000000e+00,
   

In [113]:
predict_rs=predict(server_state,features_rs)

1/1 [==============================] - 0s 49ms/step


In [114]:
predict_rs

array([[0.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [0.99999577],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]], dtype=float32)

In [115]:
labelsrs

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [116]:
merged_rs = np.concatenate((features_rs, predict_rs), axis=1)
print(merged_rs)

[[ 2.7800000e+02  6.0000000e+01  2.3000000e+01  0.0000000e+00
   7.9681277e-02  3.7000000e+01  2.2000000e+01  3.0000000e+00
   7.9200000e+02  7.0000000e+02  0.0000000e+00]
 [ 2.6600000e+02  2.2000000e+01  0.0000000e+00  0.0000000e+00
   1.1224490e-01  1.1000000e+01  6.0000000e+00  2.0000000e+01
   9.6400000e+02  4.7100000e+02  0.0000000e+00]
 [ 2.1400000e+02  1.0400000e+02  2.0000000e+00  0.0000000e+00
   2.2127660e-01  3.1000000e+01  1.0000000e+00  1.0200000e+02
   2.1600000e+02  1.1970000e+03  1.0000000e+00]
 [ 2.3500000e+02  5.2000000e+01  2.0000000e+00  0.0000000e+00
   6.6411242e-02  5.1000000e+01  1.0000000e+00  1.5000000e+01
   4.2400000e+02  1.8880000e+03  1.0000000e+00]
 [ 2.3400000e+02  4.1000000e+01  0.0000000e+00  0.0000000e+00
   8.5774057e-02  2.7000000e+01  3.0000000e+00  2.4000000e+01
   1.1000000e+01  8.7000000e+01  9.9999577e-01]
 [ 1.1200000e+02  4.0000000e+00  2.9000000e+01  0.0000000e+00
   3.0303031e-02  6.0000000e+00  2.8000000e+01  1.1000000e+01
   1.6810000e+03

In [117]:
mindex = np.concatenate((np.arange(len(merged_rs)).reshape(-1, 1), merged_rs), axis=1)


In [118]:
mindex

array([[ 0.00000000e+00,  2.78000000e+02,  6.00000000e+01,
         2.30000000e+01,  0.00000000e+00,  7.96812773e-02,
         3.70000000e+01,  2.20000000e+01,  3.00000000e+00,
         7.92000000e+02,  7.00000000e+02,  0.00000000e+00],
       [ 1.00000000e+00,  2.66000000e+02,  2.20000000e+01,
         0.00000000e+00,  0.00000000e+00,  1.12244897e-01,
         1.10000000e+01,  6.00000000e+00,  2.00000000e+01,
         9.64000000e+02,  4.71000000e+02,  0.00000000e+00],
       [ 2.00000000e+00,  2.14000000e+02,  1.04000000e+02,
         2.00000000e+00,  0.00000000e+00,  2.21276596e-01,
         3.10000000e+01,  1.00000000e+00,  1.02000000e+02,
         2.16000000e+02,  1.19700000e+03,  1.00000000e+00],
       [ 3.00000000e+00,  2.35000000e+02,  5.20000000e+01,
         2.00000000e+00,  0.00000000e+00,  6.64112419e-02,
         5.10000000e+01,  1.00000000e+00,  1.50000000e+01,
         4.24000000e+02,  1.88800000e+03,  1.00000000e+00],
       [ 4.00000000e+00,  2.34000000e+02,  4.1000000

In [119]:
sindex = mindex[mindex[:, -1].argsort()[::-1]]
sindex


array([[ 3.00000000e+00,  2.35000000e+02,  5.20000000e+01,
         2.00000000e+00,  0.00000000e+00,  6.64112419e-02,
         5.10000000e+01,  1.00000000e+00,  1.50000000e+01,
         4.24000000e+02,  1.88800000e+03,  1.00000000e+00],
       [ 2.00000000e+00,  2.14000000e+02,  1.04000000e+02,
         2.00000000e+00,  0.00000000e+00,  2.21276596e-01,
         3.10000000e+01,  1.00000000e+00,  1.02000000e+02,
         2.16000000e+02,  1.19700000e+03,  1.00000000e+00],
       [ 4.00000000e+00,  2.34000000e+02,  4.10000000e+01,
         0.00000000e+00,  0.00000000e+00,  8.57740566e-02,
         2.70000000e+01,  3.00000000e+00,  2.40000000e+01,
         1.10000000e+01,  8.70000000e+01,  9.99995768e-01],
       [ 9.00000000e+00,  8.70000000e+01,  0.00000000e+00,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.00000000e+00,  1.65000000e+02,
         8.89000000e+02,  1.27200000e+03,  0.00000000e+00],
       [ 8.00000000e+00,  9.30000000e+01,  1.9000000

In [120]:
print(sindex[:,0])
print(sindex[:,-1])

[3. 2. 4. 9. 8. 7. 6. 5. 1. 0.]
[1.         1.         0.99999577 0.         0.         0.
 0.         0.         0.         0.        ]


In [121]:
labelsrs

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.]], dtype=float32)