In [1]:
 pip install --upgrade tensorflow-federated

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 MB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 11.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.6/721.6 kB 49.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.7/73.7 MB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 57.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.7/33.7 MB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 262.5/262.5 kB 24.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 23.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.2/323.2 kB 34.7 MB/s eta 0:00:00
     ━━

In [1]:
import tensorflow as tf
import tensorflow_federated as tff

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

###Reading the Datasets

In [8]:
#Dataset1
df1 = pd.read_csv('/content/titan.csv')

In [9]:
#Dataset2
df2 = pd.read_csv('/content/dspace.csv')

In [10]:
#Dataset3
df3 = pd.read_csv('/content/dyjns.csv')

In [11]:
#Dataset4
df4 = pd.read_csv('/content/java1.csv')

In [12]:
df5=pd.read_csv("/content/jetty.csv")

In [13]:
print(df2['Failed'].unique())

[False  True]


In [14]:
df6=pd.read_csv("/content/jspirit.csv")

In [15]:
df=[df1,df2,df3,df4,df5,df6]

###Taking Necessary Columns

In [16]:
for i in range(len(df)):
  df[i]=df[i][["Test_Identifier","Failure_Count","Last_Failure_Age","Last_Failure","Failure_Rate","Transition_Count","Last_Transition","#Files_Changed","#Lines_Inserted","#Lines_Deleted","Failed"]]

In [17]:
cols=df[0].columns

In [18]:
cols

Index(['Test_Identifier', 'Failure_Count', 'Last_Failure_Age', 'Last_Failure',
       'Failure_Rate', 'Transition_Count', 'Last_Transition', '#Files_Changed',
       '#Lines_Inserted', '#Lines_Deleted', 'Failed'],
      dtype='object')

###Describing Datasets

In [19]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].info())



for dataset  1 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43257 entries, 0 to 43256
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Test_Identifier   43257 non-null  int64  
 1   Failure_Count     43257 non-null  int64  
 2   Last_Failure_Age  43257 non-null  int64  
 3   Last_Failure      43257 non-null  int64  
 4   Failure_Rate      43028 non-null  float64
 5   Transition_Count  43257 non-null  int64  
 6   Last_Transition   43257 non-null  int64  
 7   #Files_Changed    43257 non-null  int64  
 8   #Lines_Inserted   43257 non-null  int64  
 9   #Lines_Deleted    43257 non-null  int64  
 10  Failed            43257 non-null  bool   
dtypes: bool(1), float64(1), int64(9)
memory usage: 3.3 MB
None


for dataset  2 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122082 entries, 0 to 122081
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------      

###Checking For Null entries

In [20]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].isnull().sum())



for dataset  1 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Failure_Rate        229
Transition_Count      0
Last_Transition       0
#Files_Changed        0
#Lines_Inserted       0
#Lines_Deleted        0
Failed                0
dtype: int64


for dataset  2 


Test_Identifier      0
Failure_Count        0
Last_Failure_Age     0
Last_Failure         0
Failure_Rate        88
Transition_Count     0
Last_Transition      0
#Files_Changed       0
#Lines_Inserted      0
#Lines_Deleted       0
Failed               0
dtype: int64


for dataset  3 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Failure_Rate        169
Transition_Count      0
Last_Transition       0
#Files_Changed        0
#Lines_Inserted       0
#Lines_Deleted        0
Failed                0
dtype: int64


for dataset  4 


Test_Identifier       0
Failure_Count         0
Last_Failure_Age      0
Last_Failure          0
Fail

In [21]:
for i in range(len(df)):
  df[i]["Failure_Rate"] = df[i]["Failure_Rate"].fillna(-1)

<ipython-input-21-e0b4f99b3a80>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]["Failure_Rate"] = df[i]["Failure_Rate"].fillna(-1)


In [22]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i].isnull().sum())



for dataset  1 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  2 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  3 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#Files_Changed      0
#Lines_Inserted     0
#Lines_Deleted      0
Failed              0
dtype: int64


for dataset  4 


Test_Identifier     0
Failure_Count       0
Last_Failure_Age    0
Last_Failure        0
Failure_Rate        0
Transition_Count    0
Last_Transition     0
#

###Removing Inf from Failure Rate

In [23]:
for i in range(len(df)):
  print("\n\nDataset ",i+1,"\n\n")
  print(df[i]['Failure_Rate'].unique())



Dataset  1 


[-1.          0.                 inf ...  0.00436205  0.01865672
  0.00435256]


Dataset  2 


[-1.          0.          0.09090909 ...  0.00156576  0.04120879
  0.00338409]


Dataset  3 


[-1.          0.          0.25       ...  0.00966702  0.00429185
  0.0088968 ]


Dataset  4 


[-1.          0.          1.         ...  0.07107232  0.09988109
  0.05162065]


Dataset  5 


[-1.          0.          1.         ...  0.35714286  0.00859599
  0.01432665]


Dataset  6 


[-1.          0.          0.01265823  0.0125             inf  0.01234568
  0.01219512  0.01204819  0.01190476  0.01176471  0.01162791  0.01149425
  0.01136364  0.01123596  0.01111111  0.01098901  0.01086957  0.01075269
  0.0106383   0.01052632  0.01041667  0.01030928  0.01020408  0.01010101
  0.01        0.00990099  0.00980392  0.00970874  1.          0.00961538
  0.83333333  0.00952381  0.71428571  0.00943396  0.625       0.00934579
  0.55555556  0.00925926  0.5         0.00917431  0.45454545  0.0090909

In [24]:
import numpy as np

In [25]:
column_to_fix = 'Failure_Rate'
for i in range(len(df)):
  max_value = df[i][column_to_fix].replace(df[i][column_to_fix].max(), np.nan).max()
  df[i][column_to_fix] = df[i][column_to_fix].replace(df[i][column_to_fix].max(), max_value)

<ipython-input-25-a12aa10b88fd>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][column_to_fix] = df[i][column_to_fix].replace(df[i][column_to_fix].max(), max_value)


In [26]:
for i in range(len(df)):
  print("\n\nDataset ",i+1,"\n\n")
  print(df[i]['Failure_Rate'].unique())



Dataset  1 


[-1.          0.          1.         ...  0.00436205  0.01865672
  0.00435256]


Dataset  2 


[-1.          0.          0.09090909 ...  0.00156576  0.04120879
  0.00338409]


Dataset  3 


[-1.          0.          0.25       ...  0.00966702  0.00429185
  0.0088968 ]


Dataset  4 


[-1.          0.          0.9969697  ...  0.07107232  0.09988109
  0.05162065]


Dataset  5 


[-1.          0.          1.         ...  0.35714286  0.00859599
  0.01432665]


Dataset  6 


[-1.          0.          0.01265823  0.0125      1.          0.01234568
  0.01219512  0.01204819  0.01190476  0.01176471  0.01162791  0.01149425
  0.01136364  0.01123596  0.01111111  0.01098901  0.01086957  0.01075269
  0.0106383   0.01052632  0.01041667  0.01030928  0.01020408  0.01010101
  0.01        0.00990099  0.00980392  0.00970874  0.00961538  0.83333333
  0.00952381  0.71428571  0.00943396  0.625       0.00934579  0.55555556
  0.00925926  0.5         0.00917431  0.45454545  0.00909091  0.4166666

###Encoding Failed Column

In [27]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [28]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i]['Failed'].unique())



for dataset  1 


[False  True]


for dataset  2 


[False  True]


for dataset  3 


[False  True]


for dataset  4 


[False  True]


for dataset  5 


[False  True]


for dataset  6 


[False  True]


In [29]:
for i in range(len(df)):
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])

<ipython-input-29-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])
<ipython-input-29-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]['Failed'] = label_encoder.fit_transform(df[i]['Failed'])
<ipython-input-29-52b2f4f6cb97>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: ht

In [30]:
for i in range(len(df)):
  print("\n\nfor dataset ",i+1,"\n\n")
  print(df[i]['Failed'].unique())



for dataset  1 


[0 1]


for dataset  2 


[0 1]


for dataset  3 


[0 1]


for dataset  4 


[0 1]


for dataset  5 


[0 1]


for dataset  6 


[0 1]


###Creating Federated Dataset

In [31]:
from sklearn.utils import resample

In [32]:
pip install imbalanced-learn

In [33]:
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE
import pandas as pd

def upsample_failed(dataset):
    # Impute missing values
    imputer = SimpleImputer()
    dataset_imputed = pd.DataFrame(imputer.fit_transform(dataset), columns=dataset.columns)

    # Split dataset into features and target variable
    X = dataset_imputed.drop('Failed', axis=1)
    y = dataset_imputed['Failed']

    # Apply SMOTE with adjusted parameters
    smote = SMOTE(random_state=42)  # Adjust k_neighbors as needed
    X_smote, y_smote = smote.fit_resample(X, y)

    # Concatenate the original dataset with the synthetic samples
    upsampled_dataset = pd.concat([X_smote, y_smote], axis=1)

    # Shuffle the dataset
    upsampled_dataset = upsampled_dataset.sample(frac=1, random_state=42).reset_index(drop=True)

    return upsampled_dataset

In [34]:
d11 = df[0]
d22 = df[1]
d33 = df[2]
d44 = df[3]
d55=df[4]
d66=df[5]

In [35]:
import random

In [36]:
BATCH_SIZE=20

In [37]:
d1=upsample_failed(d11)

In [38]:
features1 = d1.drop(columns=['Failed']).to_numpy(dtype='float32')
labels1 = d1[['Failed']].to_numpy(dtype='float32')

In [39]:
features1[0]

array([ 5.1932213e+01,  1.7760958e+01,  4.7808376e-01,  0.0000000e+00,
        8.3621204e-01,  9.0835915e+00, -7.6095814e-01,  1.0000000e+00,
        5.8479254e+02,  7.8257745e+02], dtype=float32)

In [40]:
labels1[0]

array([1.], dtype=float32)

In [41]:
dataset1 = tf.data.Dataset.from_tensor_slices((features1, labels1))

In [42]:
dataset1=dataset1.batch(BATCH_SIZE)

In [43]:
print(dataset1.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [44]:
d2=upsample_failed(d22)

In [45]:
features2 = d2.drop(columns=['Failed']).to_numpy(dtype='float32')
labels2 = d2[['Failed']].to_numpy(dtype='float32')

In [46]:
dataset2 = tf.data.Dataset.from_tensor_slices((features2, labels2))

In [47]:
dataset2=dataset2.batch(BATCH_SIZE)

In [48]:
print(dataset2.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [49]:
d3=upsample_failed(d33)

In [50]:
features3 = d3.drop(columns=['Failed']).to_numpy(dtype='float32')
labels3 = d3[['Failed']].to_numpy(dtype='float32')

In [51]:
dataset3 = tf.data.Dataset.from_tensor_slices((features3, labels3))

In [52]:
dataset3=dataset3.batch(BATCH_SIZE)

In [53]:
print(dataset3)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [54]:
d4=upsample_failed(d44)

In [55]:
features4 = d4.drop(columns=['Failed']).to_numpy(dtype='float32')
labels4 = d4[['Failed']].to_numpy(dtype='float32')

In [56]:
dataset4 = tf.data.Dataset.from_tensor_slices((features4, labels4))

In [57]:
dataset4=dataset4.batch(BATCH_SIZE)

In [58]:
print(dataset4)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [59]:
d5=upsample_failed(d55)

In [60]:
features5 = d5.drop(columns=['Failed']).to_numpy(dtype='float32')
labels5 = d5[['Failed']].to_numpy(dtype='float32')

In [61]:
features5[0]

array([ 2.810e+02,  0.000e+00, -1.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00, -1.000e+00,  1.540e+02,  3.500e+02,  1.056e+03],
      dtype=float32)

In [62]:
labels5[0]

array([0.], dtype=float32)

In [63]:
dataset5 = tf.data.Dataset.from_tensor_slices((features5, labels5))

In [64]:
dataset5=dataset5.batch(BATCH_SIZE)

In [65]:
print(dataset5.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [66]:
d6=upsample_failed(d66)

In [67]:
features6 = d6.drop(columns=['Failed']).to_numpy(dtype='float32')
labels6 = d6[['Failed']].to_numpy(dtype='float32')

In [68]:
features6[0]

array([ 9.8338837e+01,  4.1243616e-01, -5.8756381e-01,  0.0000000e+00,
        4.1243616e-01,  0.0000000e+00, -1.0000000e+00,  2.4124362e+00,
        8.9506097e+02,  8.9574615e+02], dtype=float32)

In [69]:
labels6[0]

array([1.], dtype=float32)

In [70]:
dataset6 = tf.data.Dataset.from_tensor_slices((features6, labels6))

In [71]:
dataset6=dataset6.batch(BATCH_SIZE)

In [72]:
print(dataset6.element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [73]:
def map_func(feature, label):
    return feature, label

mapped_dataset1 = dataset1.map(map_func)
mapped_dataset2 = dataset2.map(map_func)
mapped_dataset3 = dataset3.map(map_func)
mapped_dataset4 = dataset4.map(map_func)
mapped_dataset5 = dataset5.map(map_func)
mapped_dataset6 = dataset6.map(map_func)

In [74]:
federated_data_tcp=[mapped_dataset1,mapped_dataset2,mapped_dataset3,mapped_dataset5,mapped_dataset6]

In [75]:
federated_data_tcp[0]

<_MapDataset element_spec=(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [76]:
def create_keras_model():
    return tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(10,)),
        tf.keras.layers.Dense(20),
        tf.keras.layers.Dense(1,activation='sigmoid'),
    ])

In [77]:
def model_fn():
    keras_model = create_keras_model()
    return tff.learning.models.from_keras_model(
        keras_model,
        input_spec=federated_data_tcp[0].element_spec,
        loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[tf.keras.metrics.BinaryAccuracy()]
    )

In [78]:
print(federated_data_tcp[0].element_spec)

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [79]:
@tff.tf_computation
def server_init():
  model = model_fn()
  print(model.trainable_variables)
  return model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(10, 20) dtype=float32>, <tf.Variable 'dense/bias:0' shape=(20,) dtype=float32>, <tf.Variable 'dense_1/kernel:0' shape=(20, 1) dtype=float32>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32>]


<ipython-input-79-4ad298999871>:2: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  def server_init():


In [80]:
@tf.function
def client_update(model, dataset, server_weights, client_optimizer):

  client_weights = model.trainable_variables

  tf.nest.map_structure(lambda x, y: x.assign(y),
                        client_weights, server_weights)

  for batch in dataset:
    with tf.GradientTape() as tape:

      outputs = model.forward_pass(batch)

    grads = tape.gradient(outputs.loss, client_weights)

    # Apply class weights if provided
#     if class_weights is not None:
#         grads = [grad * weight for grad, weight in zip(grads, class_weights)]
#  #class imbalance problem solved
    grads_and_vars = zip(grads, client_weights)

    client_optimizer.apply_gradients(grads_and_vars)

  return client_weights

In [81]:
@tf.function
def server_update(model, mean_client_weights):
  model_weights = model.trainable_variables
  tf.nest.map_structure(lambda x, y: x.assign(y),
                        model_weights, mean_client_weights)
  return model_weights

In [82]:
@tff.federated_computation
def initialize_fn():
  return tff.federated_value(server_init(), tff.SERVER)

In [83]:
model_weights_type = server_init.type_signature.result

In [84]:
model_weights_type

StructType([TensorType(np.float32, (10, 20)), TensorType(np.float32, (20,)), TensorType(np.float32, (20, 1)), TensorType(np.float32, (1,))]) as list

In [85]:
sample_model = model_fn()

In [86]:
sample_model.input_spec

(TensorSpec(shape=(None, 10), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))

In [87]:
tf_dataset_type = tff.SequenceType(tff.types.tensorflow_to_type(sample_model.input_spec))

In [88]:
tf_dataset_type

SequenceType(StructType([TensorType(np.float32, (None, 10)), TensorType(np.float32, (None, 1))]) as tuple)

In [89]:
@tff.tf_computation(tf_dataset_type, model_weights_type)
def client_update_fn(tf_dataset, server_weights):
  model = model_fn()
  client_optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
  return client_update(model, tf_dataset, server_weights, client_optimizer)

<ipython-input-89-8de644794af4>:1: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  @tff.tf_computation(tf_dataset_type, model_weights_type)


In [90]:
@tff.tf_computation(model_weights_type)
def server_update_fn(mean_client_weights):
  model = model_fn()
  return server_update(model, mean_client_weights)

<ipython-input-90-56510bdb54ec>:1: DeprecationWarning: `tff.tf_computation` is deprecated, use `tff.tensorflow.computation` instead.
  @tff.tf_computation(model_weights_type)


In [91]:
str(model_weights_type)

'<float32[10,20],float32[20],float32[20,1],float32[1]>'

In [92]:
federated_server_type = tff.FederatedType(model_weights_type, tff.SERVER)
federated_dataset_type = tff.FederatedType(tf_dataset_type, tff.CLIENTS)

In [93]:
@tff.federated_computation(federated_server_type, federated_dataset_type)
def next_fn(server_weights, federated_dataset):

  server_weights_at_client = tff.federated_broadcast(server_weights)

  client_weights = tff.federated_map(
      client_update_fn, (federated_dataset, server_weights_at_client))

  mean_client_weights = tff.federated_mean(client_weights)

  server_weights = tff.federated_map(server_update_fn, mean_client_weights)

  return server_weights

In [94]:
federated_algorithm = tff.templates.IterativeProcess(
    initialize_fn=initialize_fn,
    next_fn=next_fn
)

In [95]:
def evaluate(server_state):
  keras_model = create_keras_model()
  keras_model.compile(
      loss=tf.keras.losses.BinaryCrossentropy(),
        metrics=[tf.keras.metrics.BinaryAccuracy()]
  )
  keras_model.set_weights(server_state)
  keras_model.evaluate(mapped_dataset4)
  return keras_model

In [96]:
# class_weights={0:0.2,1:0.8}

In [97]:
server_state = federated_algorithm.initialize()

In [98]:
evaluate(server_state)

16418/16418 [==============================] - 67s 4ms/step - loss: 369.3941 - binary_accuracy: 0.5002


In [99]:
for round in range(30):
  server_state = federated_algorithm.next(server_state, federated_data_tcp)

In [100]:
model=evaluate(server_state)

16418/16418 [==============================] - 28s 2ms/step - loss: 8.2514 - binary_accuracy: 0.5689


In [101]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [102]:
def predict(server_state,input):
  keras_model=create_keras_model()
  keras_model.set_weights(server_state)
  predicted=keras_model.predict(input)
  return predicted

In [103]:
inp=features1

In [104]:
label=labels1

In [105]:
predicted=predict(server_state,inp)

2670/2670 [==============================] - 6s 2ms/step


In [106]:
binary_crossentropy = tf.keras.losses.BinaryCrossentropy()(label, predicted)

In [107]:
binary_crossentropy

<tf.Tensor: shape=(), dtype=float32, numpy=0.76007617>

In [108]:
binary_predictions = (predicted >= 0.5).astype(int)

In [109]:
true_values = np.array(label, dtype=int)
binary_predictions = np.array(binary_predictions, dtype=int)

In [110]:
accuracy_score(binary_predictions,true_values)

0.8228000749309231

In [111]:
report = classification_report(y_pred=binary_predictions,y_true=true_values)

In [112]:
print(report)

              precision    recall  f1-score   support

           0       0.79      0.88      0.83     42706
           1       0.87      0.76      0.81     42706

    accuracy                           0.82     85412
   macro avg       0.83      0.82      0.82     85412
weighted avg       0.83      0.82      0.82     85412



In [113]:
cnf_mat = confusion_matrix(y_true=true_values,y_pred=binary_predictions)

In [114]:
print(cnf_mat)

[[37653  5053]
 [10082 32624]]


In [115]:
print(binary_predictions)

[[1]
 [0]
 [1]
 ...
 [1]
 [0]
 [0]]


In [116]:
resampled_df1 = d4.sample(n=10)
print(resampled_df1)

        Test_Identifier  Failure_Count  Last_Failure_Age  Last_Failure  \
154061        58.000000       6.000000         32.000000           0.0   
58197        259.000000       1.000000         68.000000           0.0   
81372        238.000000      23.000000          7.000000           0.0   
212945       230.616868      90.238253          0.000000           0.0   
131444       167.588583      33.277559          0.000000           0.0   
14569        268.000000      13.935962          0.000000           0.0   
225461        67.266566       9.746056         88.495267           0.0   
273376       220.154352      33.915435          5.367815           0.0   
58738        257.205269      77.033088          9.377451           0.0   
174613       153.545980       3.247128         -0.350574           0.0   

        Failure_Rate  Transition_Count  Last_Transition  #Files_Changed  \
154061      0.021352          9.000000        31.000000       84.000000   
58197       0.007407          2.000

In [117]:
features_rs = resampled_df1.drop(columns=['Failed']).to_numpy(dtype='float32')
labelsrs = resampled_df1[['Failed']].to_numpy(dtype='float32')

In [118]:
features_rs

array([[ 5.8000000e+01,  6.0000000e+00,  3.2000000e+01,  0.0000000e+00,
         2.1352313e-02,  9.0000000e+00,  3.1000000e+01,  8.4000000e+01,
         1.8290000e+03,  4.8200000e+02],
       [ 2.5900000e+02,  1.0000000e+00,  6.8000000e+01,  0.0000000e+00,
         7.4074073e-03,  2.0000000e+00,  6.7000000e+01,  6.8000000e+01,
         1.2490000e+03,  7.1600000e+02],
       [ 2.3800000e+02,  2.3000000e+01,  7.0000000e+00,  0.0000000e+00,
         5.1918738e-02,  1.9000000e+01,  6.0000000e+00,  5.9000000e+01,
         1.7040000e+03,  1.9050000e+03],
       [ 2.3061687e+02,  9.0238251e+01,  0.0000000e+00,  0.0000000e+00,
         1.6226707e-01,  3.5836445e+01,  5.0724397e+00,  9.8177710e+00,
         1.6219463e+03,  9.8039954e+02],
       [ 1.6758858e+02,  3.3277561e+01,  0.0000000e+00,  0.0000000e+00,
         8.1899866e-02,  2.7966536e+01,  1.6555119e+00,  1.0000000e+00,
         1.1639429e+03,  7.5852167e+02],
       [ 2.6800000e+02,  1.3935962e+01,  0.0000000e+00,  0.0000000e+00,
   

In [119]:
predict_rs=predict(server_state,features_rs)

1/1 [==============================] - 0s 55ms/step


In [120]:
predict_rs

array([[0.52169377],
       [0.01078089],
       [0.99999964],
       [1.        ],
       [1.        ],
       [0.9999622 ],
       [0.04315516],
       [1.        ],
       [1.        ],
       [0.86910266]], dtype=float32)

In [121]:
labelsrs

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [122]:
merged_rs = np.concatenate((features_rs, predict_rs), axis=1)
print(merged_rs)

[[ 5.8000000e+01  6.0000000e+00  3.2000000e+01  0.0000000e+00
   2.1352313e-02  9.0000000e+00  3.1000000e+01  8.4000000e+01
   1.8290000e+03  4.8200000e+02  5.2169377e-01]
 [ 2.5900000e+02  1.0000000e+00  6.8000000e+01  0.0000000e+00
   7.4074073e-03  2.0000000e+00  6.7000000e+01  6.8000000e+01
   1.2490000e+03  7.1600000e+02  1.0780886e-02]
 [ 2.3800000e+02  2.3000000e+01  7.0000000e+00  0.0000000e+00
   5.1918738e-02  1.9000000e+01  6.0000000e+00  5.9000000e+01
   1.7040000e+03  1.9050000e+03  9.9999964e-01]
 [ 2.3061687e+02  9.0238251e+01  0.0000000e+00  0.0000000e+00
   1.6226707e-01  3.5836445e+01  5.0724397e+00  9.8177710e+00
   1.6219463e+03  9.8039954e+02  1.0000000e+00]
 [ 1.6758858e+02  3.3277561e+01  0.0000000e+00  0.0000000e+00
   8.1899866e-02  2.7966536e+01  1.6555119e+00  1.0000000e+00
   1.1639429e+03  7.5852167e+02  1.0000000e+00]
 [ 2.6800000e+02  1.3935962e+01  0.0000000e+00  0.0000000e+00
   1.4544919e-01  4.7375484e+00  3.4964423e+00  1.6787355e+01
   4.1673755e+02

In [123]:
mindex = np.concatenate((np.arange(len(merged_rs)).reshape(-1, 1), merged_rs), axis=1)

In [124]:
mindex

array([[ 0.00000000e+00,  5.80000000e+01,  6.00000000e+00,
         3.20000000e+01,  0.00000000e+00,  2.13523135e-02,
         9.00000000e+00,  3.10000000e+01,  8.40000000e+01,
         1.82900000e+03,  4.82000000e+02,  5.21693766e-01],
       [ 1.00000000e+00,  2.59000000e+02,  1.00000000e+00,
         6.80000000e+01,  0.00000000e+00,  7.40740728e-03,
         2.00000000e+00,  6.70000000e+01,  6.80000000e+01,
         1.24900000e+03,  7.16000000e+02,  1.07808858e-02],
       [ 2.00000000e+00,  2.38000000e+02,  2.30000000e+01,
         7.00000000e+00,  0.00000000e+00,  5.19187376e-02,
         1.90000000e+01,  6.00000000e+00,  5.90000000e+01,
         1.70400000e+03,  1.90500000e+03,  9.99999642e-01],
       [ 3.00000000e+00,  2.30616867e+02,  9.02382507e+01,
         0.00000000e+00,  0.00000000e+00,  1.62267074e-01,
         3.58364449e+01,  5.07243967e+00,  9.81777096e+00,
         1.62194629e+03,  9.80399536e+02,  1.00000000e+00],
       [ 4.00000000e+00,  1.67588577e+02,  3.3277561

In [125]:
sindex = mindex[mindex[:, -1].argsort()[::-1]]
sindex

array([[ 8.00000000e+00,  2.57205261e+02,  7.70330887e+01,
         9.37745094e+00,  0.00000000e+00,  1.60121873e-01,
         2.87020016e+01,  2.42185459e+01,  2.72781868e+01,
         1.48659595e+03,  8.61900757e+02,  1.00000000e+00],
       [ 7.00000000e+00,  2.20154358e+02,  3.39154358e+01,
         5.36781454e+00,  0.00000000e+00,  8.16250592e-02,
         2.29006577e+01,  4.36781454e+00,  1.79006577e+01,
         1.06536780e+03,  1.64050745e+03,  1.00000000e+00],
       [ 4.00000000e+00,  1.67588577e+02,  3.32775612e+01,
         0.00000000e+00,  0.00000000e+00,  8.18998665e-02,
         2.79665356e+01,  1.65551186e+00,  1.00000000e+00,
         1.16394287e+03,  7.58521667e+02,  1.00000000e+00],
       [ 3.00000000e+00,  2.30616867e+02,  9.02382507e+01,
         0.00000000e+00,  0.00000000e+00,  1.62267074e-01,
         3.58364449e+01,  5.07243967e+00,  9.81777096e+00,
         1.62194629e+03,  9.80399536e+02,  1.00000000e+00],
       [ 2.00000000e+00,  2.38000000e+02,  2.3000000

In [126]:
print(sindex[:,0])
print(sindex[:,-1])

[8. 7. 4. 3. 2. 5. 9. 0. 6. 1.]
[1.         1.         1.         1.         0.99999964 0.99996221
 0.86910266 0.52169377 0.04315516 0.01078089]


In [127]:
labelsrs

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)